apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://storage.googleapis.com/tekton-releases/pipeline/previous/v0.29.0/release.yaml
- https://storage.googleapis.com/tekton-releases/triggers/previous/v0.17.1/release.yaml
- https://storage.googleapis.com/tekton-releases/triggers/previous/v0.17.1/interceptors.yaml
- https://storage.googleapis.com/tekton-releases/dashboard/previous/v0.21.0/tekton-dashboard-release.yaml

patchesStrategicMerge:
- |
  $patch: delete
  apiVersion: autoscaling/v2beta1
  kind: HorizontalPodAutoscaler
  metadata:
    name: tekton-pipelines-webhook
    namespace: tekton-pipelines
- |
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: config-artifact-pvc
    namespace: tekton-pipelines
  data:
    size: 1Gi
    storageClassName: tekton
