- name: Download Helm
  get_url:
    url: '{{ helm_download_url }}'
    dest: /usr/local/src/{{ helm_download_url | basename }}

- name: Install Helm
  unarchive:
    src: /usr/local/src/{{ helm_download_url | basename }}
    dest: /usr/local/sbin
    remote_src: yes
    # In Ansible 2.11, it will be possible to use "include" instead...
    exclude:
    - linux-amd64/README.md
    - linux-amd64/LICENSE
    extra_opts:
    - --strip-components=1
    owner: root
    group: root
    mode: 0755

- name: Download the Tekton CLI
  get_url:
    url: '{{ tkn_download_url }}'
    dest: /usr/local/src/{{ tkn_download_url | basename }}

- name: Install the Tekton CLI
  unarchive:
    src: /usr/local/src/{{ tkn_download_url | basename }}
    dest: /usr/local/sbin
    remote_src: yes
    # In Ansible 2.11, it will be possible to use "include" instead...
    owner: root
    group: root
    mode: 0755
