apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- kustomize-set-image.yaml
configurations:
- tekton-image-transformer.yaml
images:
- newTag: v4.5.0
  name: k8s.gcr.io/kustomize/kustomize
- newTag: v2.26.2
  name: docker.io/alpine/git
