FROM docker.io/nginxinc/nginx-unprivileged:1.20-alpine

ARG SOURCE_TAG

USER root

RUN curl -Lo /tmp/aeneria-app.tgz https://statics.aeneria.com/aeneria-app-${SOURCE_TAG}.tar.gz \
 && mkdir -p /var/www/html \
 && tar -C /var/www/html --strip-components=1 -zxf /tmp/aeneria-app.tgz \
 && chown -R root:root /var/www/html \
 && chmod -R go+rX-w /var/www/html

ADD nginx.conf /etc/nginx/nginx.conf

USER nginx
